#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

wmname LG3D # this lets java apps render correctly - https://wiki.archlinux.org/index.php/bspwm#Problems_with_Java_applications

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         0
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a Gimp state=floating desktop='^4' follow=on
bspc rule -a Screenkey manage=off

bspc rule -a Blueman-manager state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Gnome-calculator state=floating
bspc rule -a Zathura state=tiled

bspc rule -a Slack desktop='^7' follow=on
bspc rule -a discord desktop='^7' follow=on
bspc rule -a zoom state=floating desktop='^4'
bspc rule -a "Zoom Meeting" state=floating
bspc rule -a Spotify desktop='^5'


bspc rule -a Steam desktop='^4'

# setting colors from pywal
#. "${HOME}/.cache/wal/colors.sh"
#bspc config normal_border_color "$color1"
#bspc config active_border_color "$color2"
#
#bspc config focused_border_color "$color15"
bspc config presel_feedback_color '#0b91d9'

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
